name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Create release binaries
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o emailserver-linux-amd64 ./cmd/emailserver
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o emailserver-linux-arm64 ./cmd/emailserver
        
        # Darwin AMD64
        GOOS=darwin GOARCH=amd64 go build -o emailserver-darwin-amd64 ./cmd/emailserver
        
        # Darwin ARM64 (M1/M2)
        GOOS=darwin GOARCH=arm64 go build -o emailserver-darwin-arm64 ./cmd/emailserver
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o emailserver-windows-amd64.exe ./cmd/emailserver
    
    - name: Create checksums
      run: |
        sha256sum emailserver-* > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          emailserver-*
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false

  docker:
    name: Docker Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/simple-email-server
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.production
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max